#!/bin/bash
#using numeric test comparisons
val1=10
val2=11

if test $val1 -gt 5 
	echo "The test value $val1 is greater than 5"
fi

if test $val1 -eq $val2 
then 
	echo "The values are equal"
else
	echo "The values are different"
fi